// Generated by CoffeeScript 1.6.2
(function() {
  var ASSETS, displayGameOver, displayTitle, displayWinScreen, proceedToMain, proceedToTitle;

  ASSETS = ['assets/images/arnold.png', 'assets/images/choppa.png', 'assets/images/crate.png', 'assets/images/gameover.png', 'assets/images/grass.png', 'assets/images/pregame_splash1.png', 'assets/images/pregame_splash2.png', 'assets/images/soldier.png', 'assets/images/tree.png'];

  Crafty.scene("load", function() {
    console.log("Loading started");
    Crafty.load(ASSETS, function() {
      Crafty.scene("title");
      return console.log("Loading assets");
    });
  });

  Crafty.scene("title", function() {
    displayTitle();
  });

  Crafty.scene("NextLevel", function() {
    return Crafty("LevelLoader").nextLevel();
  });

  Crafty.scene("GameOver", function() {
    return displayGameOver();
  });

  Crafty.scene("YouWin", function() {
    return displayWinScreen();
  });

  Crafty.scene("Death", function() {
    return Crafty("LevelLoader").reloadCurrentLevel();
  });

  proceedToMain = function() {
    console.log("Loading Main");
    return Crafty.scene("main");
  };

  proceedToTitle = function() {
    console.log("Loading Title");
    return Crafty.scene("title");
  };

  displayGameOver = function() {
    var gameOver, proceedTimeout;

    gameOver = Crafty.e("GameOver");
    Crafty("LevelLoader").destroy();
    Crafty("EntityFactory").destroy();
    return gameOver.bind('KeyDown', function() {
      console.log("KeyDown");
    });
  };

  displayWinScreen = function() {
    var proceedTimeout, text, win;

    win = Crafty.e("Winner");
    text = Crafty.e("2D, DOM, Color, Text, Keyboard");
    Crafty("LevelLoader").destroy();
    Crafty("EntityFactory").destroy();
    text.attr({
      x: 750,
      y: 10,
      w: 300,
      h: 100
    });
    text.textFont({
      family: "Arial",
      size: "30px"
    });
    text.textColor("white", 1);
    text.css({
      "font-size": "30px",
      "font-weight": "bold",
      "color": "white"
    });
    text.text("You got to the Choppa! You win!");
    text.bind("EnterFrame", function() {
      return text.x -= 2;
    });
    proceedTimeout = setTimeout(proceedToTitle, 10000);
    return win.bind('KeyDown', function() {
      console.log("KeyDown");
      return clearTimeout(proceedTimeout);
    });
  };

  displayTitle = function() {
    var proceedTimeout, text, title;

    title = Crafty.e("Title");
    text = Crafty.e("2D, DOM, Color, Text, Keyboard");
    text.attr({
      x: 750,
      y: 10,
      w: 600,
      h: 100
    });
    text.textFont({
      family: "Arial",
      size: "30px"
    });
    text.textColor("white", 1);
    text.css({
      "font-size": "30px",
      "font-weight": "bold",
      "color": "white"
    });
    text.text("Get to the Choppa!");
    text.bind("EnterFrame", function() {
      return text.x -= 2;
    });
    proceedTimeout = setTimeout(proceedToMain, 10000);
    return text.bind('KeyDown', function() {
      console.log("KeyDown");
      clearTimeout(proceedTimeout);
      return proceedToMain();
    });
  };

}).call(this);
